#!/usr/bin/env ruby
require 'sinatra'
require 'erubis'
require 'yaml'

configure do
  config_path = File.expand_path '~/.robot_sweatshop/compiled_config.yaml'
  config = YAML.load_file(config_path)
  set :port, ARGV[0] || 8080
  set :bind, config[:http_bind]
  set :logfile_path, config[:logfile_path]
  set :valid_logs, %w(input conveyor assembler job-dictionary payload-parser worker eye)
end

get '/reporter' do
  html = File.read "#{__dir__}/index.html.erb"
  eruby = Erubis::Eruby.new html
  context = { logs: settings.valid_logs }
  eruby.result context
end

get '/reporter/:process' do
  status 404 unless settings.valid_logs.include? params[:process]
  contents = File.read "#{settings.logfile_path}/#{params[:process]}.log"
  html = File.read "#{__dir__}/log.html.erb"
  eruby = Erubis::Eruby.new html
  context = { process: params[:process], log: contents }
  eruby.result context
end
